export const CATALOG_PRODUCTS = [
  {
    product_id: 'prod_coffee_roast',
    sku: 'SKU-HG-COFF-101',
    product_name: 'Organic Dark Roast Gourmet Coffee',
    category: 'Home Goods',
    subcategory: 'Beverages & Pantry',
    base_price: 150.0,
    unit_cost: 100.0,
    margin_pct: 0.333,
    shelf_life: '180 Days',
    seasonality: 'High Repeat Daily Demand',
    substitutability: 'High Substitutability',
    incoming_stock: 450,
    safety_stock: 120,
    lead_time: '3 Days',
    expiry: 'Dec 2026',
    holding_cost: '₹8 / unit / mo',
    event_impact: 'Diwali Morning Special (+35% Demand)',
    trend_score: '+22.4% Search Momentum',
    external_factors: 'Winter Morning Demand Surge',
    coupon_code: 'COFFEE20',
    offer_type: 'Discount & Bundle',
    avg_weekly_demand: 500
  },
  {
    product_id: 'prod_running_shoes_apex',
    sku: 'SKU-FW-APEX-202',
    product_name: 'Apex Trail Running Shoes',
    category: 'Footwear',
    subcategory: 'Athletic Footwear',
    base_price: 150.0,
    unit_cost: 78.0,
    margin_pct: 0.48,
    shelf_life: 'Non-Perishable',
    seasonality: 'Spring/Summer Peak',
    substitutability: 'Medium Substitutability',
    incoming_stock: 200,
    safety_stock: 80,
    lead_time: '5 Days',
    expiry: 'N/A',
    holding_cost: '₹15 / unit / mo',
    event_impact: 'Marathon Season Festival (+48% Demand)',
    trend_score: '+18.5% Search Interest',
    external_factors: 'Dry Outdoor Fitness Season',
    coupon_code: 'APEXRUN15',
    offer_type: 'Personalized Offer',
    avg_weekly_demand: 140
  },
  {
    product_id: 'prod_hiking_boots',
    sku: 'SKU-FW-BOOT-303',
    product_name: 'All-Terrain Waterproof Hiking Boots',
    category: 'Footwear',
    subcategory: 'Outdoor Footwear',
    base_price: 185.0,
    unit_cost: 88.8,
    margin_pct: 0.52,
    shelf_life: 'Non-Perishable',
    seasonality: 'Fall/Winter',
    substitutability: 'Low Substitutability',
    incoming_stock: 150,
    safety_stock: 60,
    lead_time: '7 Days',
    expiry: 'N/A',
    holding_cost: '₹18 / unit / mo',
    event_impact: 'Mountain Trekking Fest (+42% Demand)',
    trend_score: '+15.2% Search Momentum',
    external_factors: 'Monsoon Outdoor Weather',
    coupon_code: 'HIKEBOOT20',
    offer_type: 'Cross-sell',
    avg_weekly_demand: 95
  },
  {
    product_id: 'prod_skincare_bundle',
    sku: 'SKU-BC-CARE-1212',
    product_name: 'Hydrating Botanical Skincare Trio Bundle',
    category: 'Beauty & Care',
    subcategory: 'Facial Care',
    base_price: 78.0,
    unit_cost: 32.76,
    margin_pct: 0.58,
    shelf_life: '365 Days',
    seasonality: 'Year-round',
    substitutability: 'Low Substitutability',
    incoming_stock: 500,
    safety_stock: 150,
    lead_time: '3 Days',
    expiry: 'Nov 2027',
    holding_cost: '₹7 / unit / mo',
    event_impact: 'Bridal & Festive Glow Fest (+75% Demand)',
    trend_score: '+42.1% Search Momentum',
    external_factors: 'Clean Beauty Skincare Trend',
    coupon_code: 'BOTANICAL20',
    offer_type: 'Bundle & Coupon',
    avg_weekly_demand: 310
  },
  {
    product_id: 'prod_smartwatch_pro',
    sku: 'SKU-EL-WATCH-1616',
    product_name: 'Pro Performance Smartwatch',
    category: 'Electronics',
    subcategory: 'Wearables',
    base_price: 240.0,
    unit_cost: 115.2,
    margin_pct: 0.52,
    shelf_life: 'Non-Perishable',
    seasonality: 'High Summer Demand',
    substitutability: 'Low Substitutability',
    incoming_stock: 300,
    safety_stock: 100,
    lead_time: '5 Days',
    expiry: 'N/A',
    holding_cost: '₹16 / unit / mo',
    event_impact: 'Fitness Resolution Fest (+60% Demand)',
    trend_score: '+38.5% Search Momentum',
    external_factors: 'Health & ECG Wearable Trend',
    coupon_code: 'PROWATCH20',
    offer_type: 'Bundle & Personalized Offer',
    avg_weekly_demand: 85
  }
];
